### ISSUE TITLE
Will these listed folders and files be added in the future? 

### ISSUE THREAD

**Issue by Wer0000** [DaniloPalmeira/protanki-server#1]
ProTanki/protanki-online-backend
ProTanki/protanki-online-frontend
ProTanki/protanki-online-grpc-api
ProTanki/protanki-online-websocket-api

**Comment by DaniloPalmeira** [comment]
This repository will only be the tcp server, we will not have a client, the client you can use the one from protanki, I can send you how to modify it to work with this server

**Comment by Wer0000** [comment]
Okay, let's have you on social networks?

**Comment by Wer0000** [comment]
Come on, if it's not paid, here's my discord 0v1x#1240

**Comment by Wer0000** [comment]
Will there be further updates to the repository?

**Comment by Wer0000** [comment]
/
